import 'package:flutter/material.dart';
import '../models/app_model.dart';
import 'colors.dart';

class AppData {
  static List<BuySphereApp> getAllApps() {
    return [
      BuySphereApp(
        id: 'buyconnect',
        name: 'BuyConnect',
        shortDescription: 'Rede social completa',
        fullDescription: 'Rede social completa com perfil profissional, fotos e chat integrado',
        icon: Icons.people,
        primaryColor: BuySphereColors.buyConnect,
        features: ['Rede Social', 'Perfil Profissional', 'Galeria de Fotos', 'Chat Integrado'],
        route: '/buyconnect',
      ),
      BuySphereApp(
        id: 'buydrive',
        name: 'BuyDrive',
        shortDescription: 'Transporte e entregas',
        fullDescription: 'Transporte de pessoas e pequenas entregas com mapa interativo',
        icon: Icons.location_on,
        primaryColor: BuySphereColors.buyDrive,
        features: ['Transporte de Pessoas', 'Pequenas Entregas', 'Mapa Móvel', 'Rastreamento'],
        route: '/buydrive',
      ),
      BuySphereApp(
        id: 'buybank',
        name: 'BuyBank',
        shortDescription: 'Serviços bancários',
        fullDescription: 'Serviços bancários completos e modernos',
        icon: Icons.credit_card,
        primaryColor: BuySphereColors.buyBank,
        features: ['Conta Corrente', 'Poupança', 'Investimentos', 'Transferências'],
        route: '/buybank',
      ),
      BuySphereApp(
        id: 'buyexpress',
        name: 'BuyExpress',
        shortDescription: 'Grandes entregas',
        fullDescription: 'Grandes entregas e produtos da BuyShop via carreta',
        icon: Icons.local_shipping,
        primaryColor: BuySphereColors.buyExpress,
        features: ['Grandes Entregas', 'Produtos BuyShop', 'Transporte por Carreta', 'Rastreamento'],
        route: '/buyexpress',
      ),
      BuySphereApp(
        id: 'buymusic',
        name: 'BuyMusic',
        shortDescription: 'Streaming de música',
        fullDescription: 'Streaming de música com artistas conhecidos e novos talentos',
        icon: Icons.music_note,
        primaryColor: BuySphereColors.buyMusic,
        features: ['Músicas Conhecidas', 'Novos Artistas', 'Playlists', 'Cadastro de Cantores'],
        route: '/buymusic',
      ),
      BuySphereApp(
        id: 'buyvideo',
        name: 'BuyVideo',
        shortDescription: 'Streaming de vídeo',
        fullDescription: 'Streaming completo com filmes, séries, podcasts e canal próprio',
        icon: Icons.play_circle,
        primaryColor: BuySphereColors.buyVideo,
        features: ['Filmes e Séries', 'Conteúdo Original', 'Podcasts', 'Canal Bela', 'BuyNews'],
        route: '/buyvideo',
      ),
      BuySphereApp(
        id: 'buytravel',
        name: 'BuyTravel',
        shortDescription: 'Viagens e hospedagens',
        fullDescription: 'Viagens e hospedagens com preços exclusivos para usuários BuySphere',
        icon: Icons.flight,
        primaryColor: BuySphereColors.buyTravel,
        features: ['Comparação de Preços', 'Descontos Exclusivos', 'Hotéis Cadastrados', 'Viagens'],
        route: '/buytravel',
      ),
      BuySphereApp(
        id: 'buyfood',
        name: 'BuyFood',
        shortDescription: 'Delivery de comida',
        fullDescription: 'Entrega de todo tipo de alimento, incluindo bolos e salgados',
        icon: Icons.restaurant,
        primaryColor: BuySphereColors.buyFood,
        features: ['Todos os Alimentos', 'Bolos de Festa', 'Salgados', 'Entrega Rápida'],
        route: '/buyfood',
      ),
      BuySphereApp(
        id: 'buyfarma',
        name: 'BuyFarma',
        shortDescription: 'Entrega de medicamentos',
        fullDescription: 'Entrega de medicamentos com os melhores preços',
        icon: Icons.local_pharmacy,
        primaryColor: BuySphereColors.buyFarma,
        features: ['Medicamentos', 'Melhores Preços', 'Entrega Rápida', 'Receitas'],
        route: '/buyfarma',
      ),
      BuySphereApp(
        id: 'buyshop',
        name: 'BuyShop',
        shortDescription: 'E-commerce',
        fullDescription: 'E-commerce com promoções, lives e moedas de desconto',
        icon: Icons.shopping_cart,
        primaryColor: BuySphereColors.buyShop,
        features: ['Promoções', 'Lives', 'Moedas de Desconto', 'Produtos Variados'],
        route: '/buyshop',
      ),
      BuySphereApp(
        id: 'buycourse',
        name: 'BuyCourse',
        shortDescription: 'Cursos profissionalizantes',
        fullDescription: 'Cursos profissionalizantes online, incluindo programação e TI',
        icon: Icons.book,
        primaryColor: BuySphereColors.buyCourse,
        features: ['Cursos Profissionalizantes', 'Programação', 'TI', 'Certificados'],
        route: '/buycourse',
      ),
      BuySphereApp(
        id: 'buyuniversit',
        name: 'BuyUniversit',
        shortDescription: 'Cursos superiores',
        fullDescription: 'Cursos superiores EAD com foco em TI',
        icon: Icons.school,
        primaryColor: BuySphereColors.buyUniversit,
        features: ['Cursos Superiores', 'EAD', 'Área de TI', 'Diplomas Reconhecidos'],
        route: '/buyuniversit',
      ),
      BuySphereApp(
        id: 'buycity',
        name: 'BuyCity',
        shortDescription: 'Cidade virtual',
        fullDescription: 'Cidade virtual com lojas e realidade aumentada',
        icon: Icons.location_city,
        primaryColor: BuySphereColors.buyCity,
        features: ['Cidade Virtual', 'Lojas Virtuais', 'Realidade Aumentada', 'Aluguel de Espaços'],
        route: '/buycity',
      ),
      BuySphereApp(
        id: 'buygame',
        name: 'BuyGame',
        shortDescription: 'Games na nuvem',
        fullDescription: 'Games em geral executados na nuvem',
        icon: Icons.games,
        primaryColor: BuySphereColors.buyGame,
        features: ['Games Variados', 'Execução na Nuvem', 'Sem Download', 'Multiplayer'],
        route: '/buygame',
      ),
      BuySphereApp(
        id: 'buymessage',
        name: 'BuyMessage',
        shortDescription: 'Mensagens instantâneas',
        fullDescription: 'Mensagens instantâneas no estilo WhatsApp',
        icon: Icons.message,
        primaryColor: BuySphereColors.buyMessage,
        features: ['Mensagens de Texto', 'Áudio e Vídeo', 'Grupos', 'Status'],
        route: '/buymessage',
      ),
    ];
  }
}

